import { ScanReport } from './types'

export const DEMO_REPORT: ScanReport = {
  manifest_path: '/demo/package.json',
  target: 'https://github.com/expressjs/express',
  ecosystem: 'npm',
  total_packages: 94,
  vulnerable_packages: 5,
  critical_count: 2,
  high_count: 2,
  medium_count: 1,
  risk_summary: 'CRITICAL',
  scan_duration_seconds: 1.84,
  timestamp: new Date().toISOString(),
  circular_trust_clusters: [
    {
      nodes: ['webpack', 'loader-utils', 'webpack-dev-server', 'enhanced-resolve'],
      size: 4,
      risk_level: 'HIGH',
      max_cvss_in_cluster: 8.8,
      combined_blast_radius: 34,
    },
    {
      nodes: ['babel-core', 'babel-runtime'],
      size: 2,
      risk_level: 'LOW',
      max_cvss_in_cluster: 0,
      combined_blast_radius: 6,
    },
  ],
  blast_radius_results: [
    {
      source_node: 'lodash',
      cve_id: 'CVE-2021-23337',
      cvss_score: 9.8,
      reachable_count: 67,
      reachable_nodes: [],
      sensitive_sinks_reachable: ['mongoose', 'sqlalchemy', 'keytar'],
      sink_types: ['database', 'credential'],
      data_sensitivity: 'CRITICAL',
      blast_radius_score: 62.4,
      topological_rank: 2,
      attack_paths: [
        { path: ['lodash', 'express', 'mongoose'], sink_type: 'database', sink_node: 'mongoose', path_length: 2, exploit_score: 4.9, exploitability: 'NETWORK' },
        { path: ['lodash', 'config', 'keytar'], sink_type: 'credential', sink_node: 'keytar', path_length: 2, exploit_score: 4.9, exploitability: 'NETWORK' },
      ],
    },
    {
      source_node: 'follow-redirects',
      cve_id: 'CVE-2023-26159',
      cvss_score: 9.1,
      reachable_count: 22,
      reachable_nodes: [],
      sensitive_sinks_reachable: ['axios', 'requests'],
      sink_types: ['network'],
      data_sensitivity: 'HIGH',
      blast_radius_score: 41.2,
      topological_rank: 5,
      attack_paths: [
        { path: ['follow-redirects', 'axios'], sink_type: 'network', sink_node: 'axios', path_length: 1, exploit_score: 9.1, exploitability: 'NETWORK' },
      ],
    },
    {
      source_node: 'qs',
      cve_id: 'CVE-2022-24999',
      cvss_score: 7.5,
      reachable_count: 11,
      reachable_nodes: [],
      sensitive_sinks_reachable: ['pg'],
      sink_types: ['database'],
      data_sensitivity: 'HIGH',
      blast_radius_score: 22.1,
      topological_rank: 8,
      attack_paths: [
        { path: ['qs', 'body-parser', 'pg'], sink_type: 'database', sink_node: 'pg', path_length: 2, exploit_score: 3.75, exploitability: 'NETWORK' },
      ],
    },
    {
      source_node: 'minimist',
      cve_id: 'CVE-2021-44906',
      cvss_score: 7.3,
      reachable_count: 4,
      reachable_nodes: [],
      sensitive_sinks_reachable: [],
      sink_types: [],
      data_sensitivity: 'LOW',
      blast_radius_score: 8.4,
      topological_rank: 14,
      attack_paths: [],
    },
    {
      source_node: 'json-schema',
      cve_id: 'CVE-2021-3918',
      cvss_score: 5.6,
      reachable_count: 2,
      reachable_nodes: [],
      sensitive_sinks_reachable: [],
      sink_types: [],
      data_sensitivity: 'LOW',
      blast_radius_score: 4.1,
      topological_rank: 21,
      attack_paths: [],
    },
  ],
  minimum_patch_set: {
    packages_to_update: ['lodash', 'follow-redirects'],
    packages_to_update_count: 2,
    total_vulnerable_count: 5,
    attack_paths_eliminated: 3,
    savings_percent: 60.0,
    update_order: ['lodash', 'follow-redirects'],
    estimated_effort: 'LOW',
    reasoning: 'Steiner Tree 2-approximation selected 2 packages out of 5 to eliminate 3 attack paths. Savings: 60.0% fewer updates needed.',
  },
  patch_recommendations: [
    {
      package_name: 'lodash',
      current_version: '4.17.15',
      cve_ids: ['CVE-2021-23337', 'CVE-2020-28500'],
      cvss_score: 9.8,
      recommended_version: '4.17.21',
      threat_explanation: 'Prototype pollution via zipObjectDeep allows code injection. The attacker can manipulate object prototypes used throughout the dependency chain. This package occupies topological rank 2, amplifying blast radius to 67 downstream packages.',
      breaking_changes: 'None detected — semver-compatible patch release.',
      upgrade_command: 'npm install lodash@4.17.21',
      confidence: 'HIGH',
      attack_path_summary: 'Attacker injects malicious payload via lodash template → reaches MongoDB credential store via mongoose.',
      blast_radius_score: 62.4,
    },
  ],
}
